// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace tipTests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinClient uIForm1Client = this.UIForm1Window.UIForm1Client;
            WinEdit uITotal_Bill_BoxEdit = this.UIForm1Window.UITotal_Bill_BoxWindow.UITotal_Bill_BoxEdit;
            WinEdit uITip_AmountEdit = this.UIForm1Window.UITip_AmountWindow.UITip_AmountEdit;
            #endregion

            // Launch '%USERPROFILE%\Source\Repos\labRepo\gui_Lab\gui_Lab\bin\Debug\gui_Lab.exe'
            ApplicationUnderTest gui_LabApplication = ApplicationUnderTest.Launch(this.RecordedMethod1Params.ExePath, this.RecordedMethod1Params.AlternateExePath);

            // Click 'Form1' client
            Mouse.Click(uIForm1Client, new Point(151, 40));

            // Type '10' in 'Total_Bill_Box' text box
            uITotal_Bill_BoxEdit.Text = this.RecordedMethod1Params.UITotal_Bill_BoxEditText;

            // Type '20' in 'Tip_Amount' text box
            uITip_AmountEdit.Text = this.RecordedMethod1Params.UITip_AmountEditText;
        }
        
        /// <summary>
        /// test
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            WinButton uIComputeTipButton = this.UIForm1Window.UIComputeTipWindow.UIComputeTipButton;
            #endregion

            // Click 'Compute Tip!!!' button
            Mouse.Click(uIComputeTipButton, new Point(150, 20));
        }
        
        /// <summary>
        /// close
        /// </summary>
        public void close()
        {
            #region Variable Declarations
            WinButton uICloseButton = this.UIForm1Window.UIForm1TitleBar.UICloseButton;
            #endregion

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(24, 14));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UIForm1Window UIForm1Window
        {
            get
            {
                if ((this.mUIForm1Window == null))
                {
                    this.mUIForm1Window = new UIForm1Window();
                }
                return this.mUIForm1Window;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UIForm1Window mUIForm1Window;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\Source\Repos\labRepo\gui_Lab\gui_Lab\bin\Debug\gui_Lab.exe'
        /// </summary>
        public string ExePath = "C:\\Users\\kevin\\Source\\Repos\\labRepo\\gui_Lab\\gui_Lab\\bin\\Debug\\gui_Lab.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\Source\Repos\labRepo\gui_Lab\gui_Lab\bin\Debug\gui_Lab.exe'
        /// </summary>
        public string AlternateExePath = "%USERPROFILE%\\Source\\Repos\\labRepo\\gui_Lab\\gui_Lab\\bin\\Debug\\gui_Lab.exe";
        
        /// <summary>
        /// Type '10' in 'Total_Bill_Box' text box
        /// </summary>
        public string UITotal_Bill_BoxEditText = "10";
        
        /// <summary>
        /// Type '20' in 'Tip_Amount' text box
        /// </summary>
        public string UITip_AmountEditText = "20";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIForm1Window : WinWindow
    {
        
        public UIForm1Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Form1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinClient UIForm1Client
        {
            get
            {
                if ((this.mUIForm1Client == null))
                {
                    this.mUIForm1Client = new WinClient(this);
                    #region Search Criteria
                    this.mUIForm1Client.SearchProperties[WinControl.PropertyNames.Name] = "Form1";
                    this.mUIForm1Client.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIForm1Client;
            }
        }
        
        public UITotal_Bill_BoxWindow UITotal_Bill_BoxWindow
        {
            get
            {
                if ((this.mUITotal_Bill_BoxWindow == null))
                {
                    this.mUITotal_Bill_BoxWindow = new UITotal_Bill_BoxWindow(this);
                }
                return this.mUITotal_Bill_BoxWindow;
            }
        }
        
        public UITip_AmountWindow UITip_AmountWindow
        {
            get
            {
                if ((this.mUITip_AmountWindow == null))
                {
                    this.mUITip_AmountWindow = new UITip_AmountWindow(this);
                }
                return this.mUITip_AmountWindow;
            }
        }
        
        public UIComputeTipWindow UIComputeTipWindow
        {
            get
            {
                if ((this.mUIComputeTipWindow == null))
                {
                    this.mUIComputeTipWindow = new UIComputeTipWindow(this);
                }
                return this.mUIComputeTipWindow;
            }
        }
        
        public UIForm1TitleBar UIForm1TitleBar
        {
            get
            {
                if ((this.mUIForm1TitleBar == null))
                {
                    this.mUIForm1TitleBar = new UIForm1TitleBar(this);
                }
                return this.mUIForm1TitleBar;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIForm1Client;
        
        private UITotal_Bill_BoxWindow mUITotal_Bill_BoxWindow;
        
        private UITip_AmountWindow mUITip_AmountWindow;
        
        private UIComputeTipWindow mUIComputeTipWindow;
        
        private UIForm1TitleBar mUIForm1TitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITotal_Bill_BoxWindow : WinWindow
    {
        
        public UITotal_Bill_BoxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Total_Bill_Box";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITotal_Bill_BoxEdit
        {
            get
            {
                if ((this.mUITotal_Bill_BoxEdit == null))
                {
                    this.mUITotal_Bill_BoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITotal_Bill_BoxEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITotal_Bill_BoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITotal_Bill_BoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITip_AmountWindow : WinWindow
    {
        
        public UITip_AmountWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Tip_Amount";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITip_AmountEdit
        {
            get
            {
                if ((this.mUITip_AmountEdit == null))
                {
                    this.mUITip_AmountEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITip_AmountEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Enter Total Bill";
                    this.mUITip_AmountEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITip_AmountEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITip_AmountEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIComputeTipWindow : WinWindow
    {
        
        public UIComputeTipWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIComputeTipButton
        {
            get
            {
                if ((this.mUIComputeTipButton == null))
                {
                    this.mUIComputeTipButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIComputeTipButton.SearchProperties[WinButton.PropertyNames.Name] = "Compute Tip!!!";
                    this.mUIComputeTipButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIComputeTipButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIComputeTipButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIForm1TitleBar : WinTitleBar
    {
        
        public UIForm1TitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
}
